# Generated by Django 5.2.1 on 2025-05-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WgClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=30, verbose_name='Comment')),
                ('public_key', models.CharField(max_length=44, verbose_name="User's public key")),
                ('private_key', models.CharField(max_length=44, verbose_name="User's private key")),
                ('address', models.CharField(max_length=15, null=True, verbose_name="User's wg IP address")),
            ],
            options={
                'verbose_name': 'Wireguard client',
                'verbose_name_plural': 'Wireguard clients',
            },
        ),
    ]
